### ISSUE TITLE
"Lookup deck for AWP score" error

### ISSUE THREAD

**Issue by gereons** [keyforgerules/keyforgerules.github.io#2]
First of all, thanks for the site, I think the idea is really good!

Unfortunately, whenever I try getting one of my decks ranked, I get `TypeError: ratings[card.card_title] is undefined` (Firefox 65 on macOS). 

Two deck ids to reproduce: 21a97fe6-65d8-4ae0-8f8d-cf242d2ea049 and 8d97b7ab-fa22-4a98-9d91-566e76236c1b.

**Comment by qubitsu** [comment]
Hello @gereons ― I think you might have picked the wrong issue queue! This queue/repository is for the site here: https://keyforgerules.github.io/

**Comment by gereons** [comment]
I'm referring to https://keyforgerules.github.io/awp.html, isn't that part of this repo/site?

**Comment by qubitsu** [comment]
Whoops, I stand corrected!

**Comment by martsve** [comment]
Hello,

I am not able to reproduce the error, but I've had the same error reported before.
Can you try again with "?debug" added to the url, and save all the text in the Console after trying to look up the deck?

https://keyforgerules.github.io/awp.html?debug

**Comment by gereons** [comment]
This is what I get for deck 21a97fe6-65d8-4ae0-8f8d-cf242d2ea049

Although this is an english deck, the response returns german card names and texts, probably because my browser sends an `Accept-Language: de,en-US;q=0.7,en;q=0.3` header, and it looks like the card ratings are stored by (english) name.


data {"name":"Andersen of Aarhuvita Crucible","expansion":341,"power_level":0,"chains":0,"wins":0,"losses":0,"id":"21a97fe6-65d8-4ae0-8f8d-cf242d2ea049","is_my_deck":false,"notes":[],"is_my_favorite":false,"is_on_my_watchlist":false,"casual_wins":0,"casual_losses":0,"_links":{"houses":["Brobnar","Sanctum","Untamed"],"cards":["b361d7e2-6873-4890-8f87-702d9c89c5ad","b361d7e2-6873-4890-8f87-702d9c89c5ad","86db8510-2854-440b-8ee5-559855bb7d2c","3d650fe4-817a-4922-ba0f-297c1ebf816d","652c4e38-c4fa-4e30-8f8d-036e95249529","29eafbc7-7fc5-4239-b2a7-8bc90df1fc0f","29eafbc7-7fc5-4239-b2a7-8bc90df1fc0f","d4f666db-302f-43d0-b0af-bd03071f92ce","06ab14e9-ec4f-4f2d-908e-20940241590c","06ab14e9-ec4f-4f2d-908e-20940241590c","296dca38-e6d1-4eb3-9bdb-966e48ebedbf","435dcb07-0cd8-4851-8f82-03db793cffc7","3056e60c-8f7c-40da-951c-6e0e9cfb9d46","9a146bd4-7017-49ab-9e59-3ddbbb18d210","22fdfc0f-5ea1-42bd-984a-8c9edd8b16b7","02c7533e-98ac-48a0-94e4-621555443c8d","d71c36b7-c4be-427a-8038-2033ba9bf07e","a87f88aa-3112-4bbf-802d-24e657220734","243c5b47-3c51-4d36-a28f-227766b738c3","54ecf6b7-1343-4af2-8be9-c5810595fa92","8c062726-1b94-408d-9d5e-e5face248ea0","36b15919-4938-4e83-b57e-ae3a6b83cbbd","a8b24d43-1940-4852-afcb-d034d99da55d","a8b24d43-1940-4852-afcb-d034d99da55d","f96b20b3-df0e-4d43-a737-e7fa56ff690b","f96b20b3-df0e-4d43-a737-e7fa56ff690b","469dd68d-cdd6-40e0-8fc9-a167c45a9aea","f04a582c-c50b-453e-afc8-9d459c46cc22","afe27535-5cb7-43a1-8eab-ff9a6a472edb","f0c4cb0f-8e5f-454c-a6ad-35f35ac3c98a","f0c4cb0f-8e5f-454c-a6ad-35f35ac3c98a","3680b506-9a5c-4afb-956d-15b08d1e9ecc","ddd62eb0-4699-4fb0-9b63-43769186b509","02feb5dd-81a0-4e06-8b5d-0ad7bdc9de08","dc0ba4ea-6f6e-475f-899c-88ad45ccae94","05fa104f-3719-41d0-9189-57ff3ec5edc1"]}} data.js:134:14
cards 
[{"id":"469dd68d-cdd6-40e0-8fc9-a167c45a9aea","card_title":"Greifranken","house":"Untamed","card_type":"Action","front_image":"https://cdn.keyforgegame.com/media/card_front/de/341_324_VH9R4P26824V_de.png","card_text":"Spielen: Schicke bis zu 3 Artefakte auf die Hand ihrer jeweiligen Besitzer zurück.","traits":"","amber":1,"power":0,"armor":0,"rarity":"Uncommon","flavor_text":"","card_number":324,"expansion":341,"is_maverick":false},{"id":"243c5b47-3c51-4d36-a28f-227766b738c3","card_title":"Reiter des Hungers","house":"Sanctum","card_type":"Creature","front_image":"https://cdn.keyforgegame.com/media/card_front/de/341_247_H927W8WQRH5X_de.png","card_text":"Spielen/Kampf/Ernte: Zerstöre die schwächste Kreatur.","traits":"Reiter • Geist","amber":0,"power":5,"armor":0,"rarity":"FIXED","flavor_text":"Einer nimmt das Leben.","card_number":247,"expansion":341,"is_maverick":false},{"id":"d71c36b7-c4be-427a-8038-2033ba9bf07e","card_title":"Feldherr Remiel","house":"Sanctum","card_type":"Creature"…
data.js:135:14
dictionary 
{"469dd68d-cdd6-40e0-8fc9-a167c45a9aea":{"id":"469dd68d-cdd6-40e0-8fc9-a167c45a9aea","card_title":"Greifranken","house":"Untamed","card_type":"Action","front_image":"https://cdn.keyforgegame.com/media/card_front/de/341_324_VH9R4P26824V_de.png","card_text":"Spielen: Schicke bis zu 3 Artefakte auf die Hand ihrer jeweiligen Besitzer zurück.","traits":"","amber":1,"power":0,"armor":0,"rarity":"Uncommon","flavor_text":"","card_number":324,"expansion":341,"is_maverick":false},"243c5b47-3c51-4d36-a28f-227766b738c3":{"id":"243c5b47-3c51-4d36-a28f-227766b738c3","card_title":"Reiter des Hungers","house":"Sanctum","card_type":"Creature","front_image":"https://cdn.keyforgegame.com/media/card_front/de/341_247_H927W8WQRH5X_de.png","card_text":"Spielen/Kampf/Ernte: Zerstöre die schwächste Kreatur.","traits":"Reiter • Geist","amber":0,"power":5,"armor":0,"rarity":"FIXED","flavor_text":"Einer nimmt das Leben.","card_number":247,"expansion":341,"is_maverick":false},"d71c36b7-c4be-427a-8038-2033ba9bf07e"…
data.js:142:14
Add card  b361d7e2-6873-4890-8f87-702d9c89c5ad data.js:153:16
\> card  
Object { id: "b361d7e2-6873-4890-8f87-702d9c89c5ad", card_title: "Zorn", house: "Brobnar", card_type: "Action", front_image: "https://cdn.keyforgegame.com/media/card_front/de/341_1_7C854VPW72RH_de.png", card_text: "Spielen: Mache eine befreundete Kreatur spiel­bereit und lasse sie kämpfen. (Jene Kreatur darf zu einer beliebigen Fraktion gehören.)", traits: "", amber: 1, power: 0, armor: 0, … }

**Comment by gereons** [comment]
Removing `de` from the `Accept-Language` header does make the site work.

**Comment by martsve** [comment]
I have changed the lookup key from Card name to ExpansionName + CardNumber. It should now work for any accept language.

**Comment by gereons** [comment]
Thanks, works like a charm!
