### ISSUE TITLE
[Q] Any plans to update AWP for AoA?

### ISSUE THREAD

**Issue by gereons** [keyforgerules/keyforgerules.github.io#5]

**Comment by martsve** [comment]
Yes, but I'm having trouble with the API at the moment. 
I'm getting a lot of TooManyRequests-errors which I'm not sure why I'm getting. I'll probably have to implement some delay between calls.

**Comment by martsve** [comment]
Adding a 1s delay between each call seems to fix the problem. Will update results and parsing of new cards within a few days!

**Comment by gereons** [comment]
Thanks, your work is much appreciated!

**Comment by martsve** [comment]
Ratings have now been updated. 
I will work on some set indicators and seperation between sets later.
