### ISSUE TITLE
v1.5 rules update

### ISSUE THREAD

**Issue by legopin** [keyforgerules/keyforgerules.github.io#9]
Hello, I noticed that the last update was at 1.3.

Do you have plans to update? Do you accept pull requests to update the README document?

Are there plans to keep separate versions available?

https://images-cdn.fantasyflightgames.com/filer_public/dc/a5/dca58aae-3c00-4857-9387-06735cc8a9cd/keyforge_rulebook_v11-compressed.pdf

**Comment by martsve** [comment]
Sadly I have lost interest in Keyforge after Fantasy Flight added timing restrictions to their API making it difficult to download all decks and match results. 

However, I will gladly accept pull requests :)
